apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
  namespace: mimir
  labels:
    app: metrics-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
    spec:
      containers:
      - name: metrics-generator
        image: prom/prometheus:v2.45.0
        args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus
          - --web.console.libraries=/usr/share/prometheus/console_libraries
          - --web.console.templates=/usr/share/prometheus/consoles
          - --web.enable-lifecycle
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: tls-certs
          mountPath: /etc/prometheus/tls
          readOnly: true
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTPS
          initialDelaySeconds: 45
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: tls-certs
        secret:
          secretName: mimir-tls-certs 