apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: mimir
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
    remote_write:
      - url: https://mimir-nginx.mimir.svc:8443/api/v1/push
        tls_config:
          ca_file: /etc/prometheus/tls/ca.crt
          cert_file: /etc/prometheus/tls/tls.crt
          key_file: /etc/prometheus/tls/tls.key
          insecure_skip_verify: true
        headers:
          X-Scope-OrgID: "default"