apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mimir.fullname" . }}-traefik-crd
  labels:
    app.kubernetes.io/name: {{ include "mimir.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: traefik
rules:
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - secrets
    verbs: ["get", "list", "watch"] 