apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mimir.fullname" . }}-traefik-crd
  labels:
    app.kubernetes.io/name: {{ include "mimir.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mimir.fullname" . }}-traefik-crd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }} 