apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.fullname" . }}-traefik-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mimir.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: traefik
data:
  traefik.yaml: |
    api:
      dashboard: true
      insecure: true
    
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      file:
        directory: /etc/traefik/ingress
        watch: true
        debugLogGeneratedTemplate: true
    
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
      admin:
        address: ":8081"
      metrics:
        address: ":8082"

    log:
      level: "DEBUG" 
